name: Build RT-Plugins

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t rt-plugins .

    - name: Run build in Docker container
      run: |
        docker run --rm rt-plugins /bin/sh -c "
          mkdir build && cd build && \
          cmake .. && \
          make && \
          make install
        "

    - name: Check build artifacts
      run: |
        docker run --rm rt-plugins /bin/sh -c "
          ls -l /usr/local/lib/ladspa
        "
